# application.yml
--- 
spring: 
  application: 
    name: connessioni
  cloud:
    consul:
      host: consul
      port: 8500
      discovery: 
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        # configurazione per effettuare esprimenti, NON USARE UN PRODUZIONE 
        # dopo quanto tempo consul deve smettere di restituire servizi che non rispondono all'health check? 
        healthCheckCriticalTimeout: 45s
        # consul deve restituire solo servizi che passano l'health check (default=false) 
        queryPassing: true 
    loadbalancer: 
      ribbon.enabled: false 
  datasource:
    url: jdbc:postgresql://db-connessioni:5432/connessionidb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      #database-platform: org.hibernate.dialect.PostgreSQL82Dialec
      show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    #KAFKA PRODUCER
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#MESSAGING
asw:
  edipogram:
    connessioni:
      channel:
        out: connessione-created-service-event-channel
      #group-id: connessioni-producer

server: 
#  port: ${PORT:${SERVER_PORT:0}}
  port: 8080

# fa il logging dei comandi sql eseguiti 
#spring.jpa.show-sql: true
# disable OSIV
spring.jpa.open-in-view: false

spring.kafka.consumer.properties.spring.json.trusted.packages: asw.edipogram.*
