version: '3'
services:
  consul:
    image: consul:latest
    container_name: consul
    hostname: consul
    ports:
      - "8500"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - "zookeeper"
    ports:
      - "9092"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      #      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.11.121:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      #- KAFKA_CREATE_TOPICS:"enigma-created-service-event-channel:4:1,connessione-created-service-event-channel:4:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api-gateway:
    build: ./api-gateway
#    image: chila99/edipogram-api-gateway:2022
    ports:
      - "8080:8080"
    depends_on:
      - "consul"

  enigmi:
    build: ./enigmi
#    image: chila99/edipogram-enigmi:2022
    depends_on:
      - "consul"
      - "db-enigmi"

  connessioni:
    build: ./connessioni
#    image: chila99/edipogram-connessioni:2022
    depends_on:
      - "consul"
      - "db-connessioni"

  enigmi-seguiti:
    build: ./enigmi-seguiti
#    image: chila99/edipogram-enigmi-seguiti:2022
    depends_on:
      - "consul"
      - "db-enigmiseguiti"

  db-enigmi:
    image:
      postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=enigmidb
    ports:
      - "5432"
#    volumes:
#      - ./database/db-enigmi:/var/lib/postgresql/data

  db-connessioni:
    image:
      postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=connessionidb
    ports:
      - "5432"
#    volumes:
#      - ./database/db-connessioni:/var/lib/postgresql/data

  db-enigmiseguiti:
    image:
      postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=enigmiseguitidb
    ports:
      - "5432"
#    volumes:
#      - ./database/db-enigmiseguiti:/var/lib/postgresql/data